### ISSUE TITLE
TFLite conversion (post-GSoC)

### ISSUE THREAD

**Issue by sayakpaul** [AdityaKane2001/regnety#16]
Since one of the claims of the paper was improved inference latency of RegNets even of mobile phones, I think it might be a good idea to try to convert the RegNet models to TFLite and benchmark them.

A couple of resources that might be helpful:

* [Post-training quantization](https://www.tensorflow.org/lite/performance/post_training_quantization)
* [TFLite Benchmark](https://www.tensorflow.org/lite/performance/measurement)

**Comment by AdityaKane2001** [comment]
Closing this, will continue in #19
