### ISSUE TITLE
TFHub PR

### ISSUE THREAD

**Issue by AdityaKane2001** [AdityaKane2001/regnety#17]
Opening this issue for TFHub PR related discussions.

**Comment by AdityaKane2001** [comment]
@sayakpaul @MorganR 

As you know, we have 4 variants of the same model. In this case, how exactly should I keep the documentation structure?

AFAIK I need to do something like this:

```
.
└── assets/docs/
    └── adityakane2001/
        ├── models/
        │   ├── RegNetY 200MF/
        │   │   └── 1.md
        │   ├── RegNetY 400MF/
        │   │   └── 1.md
        │   ├── RegNetY 600MF/
        │   │   └── 1.md
        │   └── RegNetY 800MF/
        │       └── 1.md
        └── adityakane2001.md

```
Just 👍 this if you think this structure is correct.

**Comment by AdityaKane2001** [comment]
@sayakpaul 

Updated the models in he GCS bucket.

**Comment by sayakpaul** [comment]
Which models?

**Comment by AdityaKane2001** [comment]
The 600 and 800 MF ones. Their improved versions. Now training 400Mf

**Comment by sayakpaul** [comment]
Cool. Hub models are immutable i.e. once they are merged then changing them in the source won't make any sense. So, please be aware.

**Comment by sayakpaul** [comment]
I think we can close this now? All the Hub-related discussions should take on your corresponding Hub PR.
